name: TouhouMC_Races_Basic
main: net.TouhouMC.noteumaple.TouhouMC_Races_Basic.TouhouMC_Races_Basic
author: noteumaple
version: 0.5
commands:
   tmcr:
      description: Base Command
      aliases: [touhoumcraces,races]
